{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {},
     "inputWidgets": {},
     "nuid": "b3b5e454-3d82-4a6b-8881-1073f3b626c8",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "source": [
    "#  Delivery_Unit_Economics: Pipeline ETL para Análise de P&L Unitário (CRISP-DM)\n",
    "\n",
    "Este repositório contém o pipeline de dados completo (Bronze, Silver, Gold) construído em **Databricks/Spark SQL** para calcular a **Unit Economics (UE)** de um **Marketplace Two-Sided** de entregas. O objetivo final é fornecer uma base sólida e dimensional para análise de Profit & Loss (P&L) no Power BI.\n",
    "\n",
    "---\n",
    "\n",
    "##  Objetivo de Negócio\n",
    "\n",
    "**Contexto:** Plataforma de entregas (Two-Sided Marketplace) conectando Lojas (fornecedores) e Motoristas (logística) a Clientes.\n",
    "\n",
    "**Meta:** Determinar a **Margem de Contribuição (Lucro Bruto Unitário)** por pedido. O pipeline calcula todas as métricas financeiras essenciais (GMV, Receita de Comissão, COGS Logístico e Transacional) para permitir otimizações estratégicas por segmento de loja, região e tempo.\n",
    "\n",
    "---\n",
    "\n",
    "##  Estrutura do Pipeline e Camadas (CRISP-DM)\n",
    "\n",
    "O projeto está dividido em três camadas do Delta Lake, correspondendo às etapas de Preparação e Modelagem do CRISP-DM.\n",
    "\n",
    "### 1. Camada BRONZE (Ingestão e Fidelidade)\n",
    "\n",
    "**Fase CRISP-DM:** Data Preparation (Raw)\n",
    "**Descrição:** Zona de aterrissagem dos dados brutos. O foco é a ingestão atômica e a padronização das chaves primárias.\n",
    "\n",
    "| Fonte (CSV) | Chave Padronizada | Observações Técnicas |\n",
    "| :--- | :--- | :--- |\n",
    "| `orders` | `order_id` | Fonte principal de tempo e valores brutos. |\n",
    "| `deliveries` | `delivery_order_id` -> `order_id` | Correção da chave e tratamento do `delivery_status` (`DELIVERED`). |\n",
    "| `payments` | `payment_order_id` -> `order_id` | Correção da chave e valores de pagamento. |\n",
    "| `stores`, `hubs` | `store_id`, `hub_id` | Ingestão das dimensões para enriquecimento futuro. |\n",
    "\n",
    "**Scripts:** `sql/01_bronze_ingestion/`\n",
    "\n",
    "### 2. Camada SILVER (Cálculo e Unificação da UE)\n",
    "\n",
    "**Fase CRISP-DM:** Data Preparation (Transformation)\n",
    "**Descrição:** Aplicação da lógica de negócio e cálculo da Unit Economics. Esta camada é o **coração** do P&L unitário.\n",
    "\n",
    "**Lógica Central:**\n",
    "1. **Filtro de Status:** Apenas pedidos com `delivery_status = 'DELIVERED'` são considerados.\n",
    "2. **Junção:** `INNER JOIN` entre as três tabelas de fatos (`orders`, `deliveries`, `payments`) para garantir que o pedido foi pago e entregue.\n",
    "3. **Cálculo de Métricas:** Aplicação de premissas de negócio (vide `docs/business_rules.md`) para derivar:\n",
    "    * **Receita Líquida Plataforma:** (Comissão da Loja) + (Margem da Taxa de Entrega).\n",
    "    * **COGS Logístico Simulado:** Repasse do Entregador (custo variável).\n",
    "    * **Lucro Bruto Unitário (Margem de Contribuição)**.\n",
    "\n",
    "**Tabela Resultante:** `pl_delivery_analysis.tbl_fact_pedidos_silver`\n",
    "**Scripts:** `sql/02_silver_unit_economics/`\n",
    "\n",
    "### 3. Camada GOLD (BI e Modelo Dimensional)\n",
    "\n",
    "**Fase CRISP-DM:** Modeling\n",
    "**Descrição:** Criação de um **Modelo Dimensional Star Schema**  para consumo otimizado no Power BI.\n",
    "\n",
    "| Tabela (Gold) | Tipo | Chaves | Justificativa Técnica |\n",
    "| :--- | :--- | :--- | :--- |\n",
    "| `tbl_fato_delivery_gold` | **Fato** | `order_date_key`, `store_id`, `driver_id` | Contém 419.343 linhas e todas as métricas de UE. |\n",
    "| `tbl_dim_store_gold` | **Dimensão** | `store_id` | Enriquecida com `city` via **LEFT JOIN** em `tbl_dim_hubs_bronze`. |\n",
    "| `tbl_dim_time_gold` | **Dimensão** | `date_key` | Criada a partir do `created_at_ts_str` após correção da conversão de formato (`M/d/yyyy h:mm:ss a`). |\n",
    "\n",
    "**Scripts:** `sql/03_gold_dimensional_model/`\n",
    "\n",
    "---\n",
    "\n",
    "##  Setup e Execução\n",
    "\n",
    "### Pré-requisitos\n",
    "* Cluster Databricks ou Spark SQL configurado.\n",
    "* Dados brutos nos volumes do Unity Catalog: `/Volumes/workspace/pl_delivery_analysis/raw_data_volume/`\n",
    "\n",
    "### Ordem de Execução\n",
    "\n",
    "1. Execute todos os scripts em `sql/01_bronze_ingestion/`.\n",
    "2. Execute o script em `sql/02_silver_unit_economics/`.\n",
    "3. Execute os scripts em `sql/03_gold_dimensional_model/` (na ordem 01, 02, 03).\n",
    "\n",
    "---\n",
    "\n",
    "##  Conexão com o Power BI (Deployment)\n",
    "\n",
    "A análise final é feita conectando o Power BI ao Catálogo/Schema `workspace.pl_delivery_analysis` e carregando as três tabelas `_gold`. As chaves de relacionamento devem ser estabelecidas no Power BI para formar o *Star Schema*."
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": null,
   "dashboards": [],
   "environmentMetadata": {
    "base_environment": "",
    "environment_version": "4"
   },
   "inputWidgetPreferences": null,
   "language": "python",
   "notebookMetadata": {
    "pythonIndentUnit": 4
   },
   "notebookName": "README",
   "widgets": {}
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
